FROM node:21.7.1-alpine3.19

# Create app directory
WORKDIR /usr/src/app

COPY . .

RUN apk update && apk upgrade
RUN apk add --no-cache git nano 

# If you are building your code for production
# RUN npm ci --only=production
RUN npm ci --verbose

CMD node src/server.js 