name: Development workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build --if-present
      - name: Create .env with Github Secrets and run script
        run: |
          touch .env
          echo FLICKR_API_KEY=$FLICKR_API_KEY >> .env
          echo MONGO_URL=$MONGO_URL >> .env
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
      - run: npm test

        
